from swimlane.exceptions import InvalidSwimlaneBuildVersion as InvalidSwimlaneBuildVersion

def compare_versions(version_a: str, version_b: str, zerofill: bool = ...): ...
def requires_swimlane_version(min_version: str | None = ..., max_version: str | None = ...): ...
def get_package_version(): ...
