from swimlane.core.resources.base import APIResource as APIResource

class ResourcesCache:
    def __init__(self, per_cache_max_size: int) -> None: ...
    def __len__(self): ...
    def __contains__(self, item: APIResource): ...
    def __getitem__(self, item: APIResource): ...
    def __delitem__(self, resource: APIResource) -> None: ...
    def cache(self, resource: APIResource) -> None: ...
    def clear(self, *resource_types: APIResource) -> None: ...

def get_cache_index_key(resource: APIResource): ...
def check_cache(resource_type: APIResource): ...
