class Cursor:
    def __init__(self) -> None: ...
    def __len__(self): ...
    def __iter__(self): ...
    def __getitem__(self, item): ...

class PaginatedCursor(Cursor):
    default_limit: int
    default_page_size: int
    page_size: int
    def __init__(self, limit: int = ..., page_size: int = ...) -> None: ...
