from typing import Any, Dict

from swimlane.core.client import Swimlane
from swimlane.core.resolver import SwimlaneResolver as SwimlaneResolver

class APIResourceMetaclass(type):
    def __call__(cls, *args, **kwargs): ...

class APIResource:
    _raw: Dict[str, Any]

    def __init__(self, swimlane: Swimlane, raw: Dict[str, Any]) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other: Any): ...
    def __ne__(self, other: Any): ...
    def get_cache_internal_key(self): ...
    def get_cache_index_keys(self) -> None: ...
